routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Route::group(['prefix' => 'admin'], function () {
	Route::group(['middleware' => ['auth']], function () {
		Route::get('/','AdminController@index');
		Route::resource('page', 'PageController');
		Route::resource('categorie', 'CategorieController');
		Route::resource('choristes', 'UserController');

	});

});
/*
Route::get('page/{categorie}/{slug}','PageController@showpublic')->name('public_page');*/
Route::get('categorie/{slug}','CategorieController@showpublic')->name('public_categ');
Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/contact', 'PageController@show_contact');

resources/views/admin/page/create.blade.php
@extends('layouts.admin.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form method="post" role="form"  action="{{ route('page.store') }}">
                    {{ csrf_field() }}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="field">
                            <p class="control">
                                <input class="input" type="text" name="pagename" placeholder="Nom de la page">
                            </p>
                        </div>
                    </div>

                    <div class="field">
                        <label class="label">Catégorie de page</label>
                        <p class="control">
                            <span class="select">
                              <select name="id_categ">
                                 @foreach($categs as $categ)
                                      <option value="{{$categ->id}}">{{$categ->name}}</option>
                                  @endforeach
                              </select>
                            </span>
                        </p>
                    </div>




                    <div class="panel-body">
                            <textarea name="mytextarea"  id="mytextarea" class="ckeditor">Hello, World!</textarea>
                            <button type="submit" class="button">Ajout</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/page/edit.blade.php
@extends('layouts.admin.admin')

@section('content')

        <div class="row">
            <div class="col-md-8 col-md-offset-1">

                <form method="post" role="form"  action="{{ route('page.update', $page->id) }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="PATCH">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="field">
                                <label class="label">Modification de :  {{ $page->title }}</label>
                                <p class="control">
                                    <input class="input" type="text" name="title" placeholder="Nom de la page" value=" {{ $page->title }}">
                                </p>
                            </div>
                        </div>

                        <div class="panel-body">
                            <textarea name="content"  id="mytextarea" class="ckeditor"> {{ $page->content }}</textarea>
                            <button type="submit" class="button">Modifier</button>

                        </div>

                    </div>

                </form>
            </div>
        </div>


@endsection

resources/views/admin/page/index.blade.php
@extends('layouts.admin.admin')
@section('content')

    <section class="section">

        <div class="container">

            {{--
                        <h1 class="title">{{ $page->title }}</h1>
                        <div class='body'>
                            <p> {!! $page->content !!}</p>
                        </div>
            --}}

            <a class="button is-primary" href="{{route('page.create')}}">Ajouter</a>


            <table class="table">
                <thead>
                <tr>
                    <th>
                        Titre
                    </th>
                    <th>
                        Auteur
                    </th>
                    <th>
                        Date de publication
                    </th>
                    <th>
                        Date de modification
                    </th>
                </tr>
                </thead>
                <tbody>

                @forelse($page as $p)
                    <tr>

                        <th>
                            @php
                                $categ = DB::table('categories')->where('id', $p->categorie_id)->first();;

                            @endphp
                            <a href="{{ route('page.edit', [$p->id]) }}">
                                {{ $p->title }}
                            </a>
                        </th>
                        <th>
                            <a href="{{ route('page.show', $p->id) }}">
                                Voir
                            </a>
                        </th>
                    </tr>
                @empty
                    <p>Il n'y a pas de page à afficher ! </p>

                @endforelse
                </tbody>
            </table>

        </div>

    </section>

@stop

resources/views/admin/page/show.blade.php
@extends('layouts.admin.admin')
@section('content')

    <section class="section">

        <div class="container">

            <h1 class="title">{{ $page->title }}</h1>
            <div class='body'>
               <p> {!! $page->content !!}</p>
            </div>
        </div>

    </section>

@stop