routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Route::group(['prefix' => 'admin'], function () {
	Route::group(['middleware' => ['auth']], function () {
		Route::get('/','AdminController@index');
		Route::resource('page', 'PageController');
		Route::resource('categorie', 'CategorieController');
		Route::resource('choristes', 'UserController');

	});

});
/*
Route::get('page/{categorie}/{slug}','PageController@showpublic')->name('public_page');*/
Route::get('categorie/{slug}','CategorieController@showpublic')->name('public_categ');
Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/contact', 'PageController@show_contact');

resources/views/layouts/admin/admin.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bulma.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <!-- Scripts -->
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>



</head>
<body>
<div id="app">
    @include('layouts.menu')
    <div class="columns">
        <div class="column is-2">
            @include('layouts.admin.left_menu')
        </div>
        <div class="column espace_top_logo">
            @if (session('status'))
                <div class="alert alert-success">
                    {{ session('status') }}
                </div>
            @endif

            @yield('content')
        </div>
    </div>


    @include('layouts.footer')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
<script>
    var options = {
        filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
        filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
        filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
        filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}'
    };
</script>



<script type="text/javascript">
    CKEDITOR.replace( 'mytextarea',options)
</script>
</body>
</html>

resources/views/layouts/admin/left_menu.blade.php
<aside class="menu" id="menu">
    <p class="menu-label">
        General
    </p>
    <ul class="menu-list">
        <li><a href="{{route('choristes.index')}}">Choristes</a></li>
        <li><a>Customers</a></li>
    </ul>
    <p class="menu-label">
        Administration
    </p>
    <ul class="menu-list">
        <li  ><a href="{{route('page.index')}}">Pages</a></li>
        <li>
            <a class="{{route('page.create')}}">Ajouter une page</a>
            <ul>
                <li><a href="/admin/categorie/">Catégories de page</a></li>
               {{-- <li><a>Plugins</a></li>
                <li><a>Add a member</a></li>--}}
            </ul>
        </li>
       {{-- <li><a>Invitations</a></li>
        <li><a>Cloud Storage Environment Settings</a></li>
        <li><a>Authentication</a></li>--}}
    </ul>
    <p class="menu-label">
        Transactions
    </p>
    <ul class="menu-list">
        <li><a>Payments</a></li>
        <li><a>Transfers</a></li>
        <li><a>Balance</a></li>
    </ul>
</aside>