routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'IndexController@index');

Route::group(['prefix' => 'admin'], function () {
	Route::group(['middleware' => ['auth']], function () {
		Route::get('/','AdminController@index');
		Route::resource('page', 'PageController');
		Route::resource('categorie', 'CategorieController');
		Route::resource('choristes', 'UserController');

	});

});
/*
Route::get('page/{categorie}/{slug}','PageController@showpublic')->name('public_page');*/
Route::get('categorie/{slug}','CategorieController@showpublic')->name('public_categ');
Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/contact', 'PageController@show_contact');

app/Categorie.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categorie extends Model
{
	public $timestamps = false;
	protected $fillable = ['name', 'description','slug'];
}

app/Http/Controllers/CategorieController.php
<?php

namespace App\Http\Controllers;

use App\Categorie;
use App\Http\Requests\StorePagePost;
use Illuminate\Http\Request;
use Illuminate\Session\Store;

class CategorieController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
	/**
	 * Display a listing of the resource.
	 *
	 * @param \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function index(Request $request)
	{
		$page = Categorie::all();
		if ($request->is('admin/categorie')) {
			return view('admin.categorie.index', compact('page'));
		}



	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create()
	{
		return view('admin.categorie.create');
	}


	public function store(StorePagePost $request)
	{
		$pagename = $request->input('pagename');
		$content = $request->input('mytextarea');
		$slug = preg_replace('/\s+/', '-', $pagename);

		$page = new Categorie;
		$p = $page::firstOrCreate(['name' => $pagename, 'slug' =>$slug, 'description' => $content]);
		$id = $p->id;
		return redirect('admin/categorie/show/'.$id);
	}


	/**
	 * @param $id
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function show($id)
	{
		$page = Categorie::findOrFail($id);
		return view('admin.categorie.show', compact('page'));
	}

	public function showpublic($slug)
	{
		$page = Categorie::where('slug','=',$slug)->first();
		return view('show_categ', compact('page'));
	}

	/**
	 * @param $id
	 *
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function edit($id)
	{
		$page = Categorie::findOrFail($id);
		return view('admin.page.edit', compact('page'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param \App\Categorie            $categorie
	 *
	 * @return \Illuminate\Http\Response
	 * @internal param \App\Page $page
	 */
	public function update(Request $request, Categorie $categorie)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param \App\Categorie $categorie
	 *
	 * @return \Illuminate\Http\Response
	 * @internal param \App\Page $page
	 */
	public function destroy(Categorie $categorie)
	{
		//
	}
}

resources/views/admin/categorie/create.blade.php
@extends('layouts.admin.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <form method="post" role="form"  action="{{ route('ajout_categ') }}">
                    {{ csrf_field() }}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="field">
                            <label class="label">Nom de la catégorie</label>
                            <p class="control">
                                <input class="input" type="text" name="pagename" placeholder="Nom de la catégorie">
                            </p>
                        </div>
                    </div>

                    <div class="panel-body">
                            <textarea name="mytextarea"  id="mytextarea" class="ckeditor"></textarea>
                            <button type="submit" class="button">Ajout</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categorie/edit.blade.php
@extends('layouts.admin.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">

                <form method="post" role="form"  action="{{ route('ajout_page') }}">
                    {{ csrf_field() }}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <div class="field">
                                <label class="label">Modification de :  {{ $page->title }}</label>
                                <p class="control">
                                    <input class="input" type="text" name="pagename" placeholder="Nom de la page" value=" {{ $page->title }}">
                                </p>
                            </div>
                        </div>

                        <div class="panel-body">
                            <textarea name="mytextarea"  id="mytextarea" class="ckeditor"> {{ $page->content }}</textarea>
                            <button type="submit" class="button">Ajout</button>
                </form>
            </div>
        </div>
    </div>
    </div>
    </div>
@endsection

resources/views/admin/categorie/index.blade.php
@extends('layouts.admin.admin')
@section('content')

    <section class="section">

        <div class="container">

            {{--
                        <h1 class="title">{{ $page->title }}</h1>
                        <div class='body'>
                            <p> {!! $page->content !!}</p>
                        </div>
            --}}

            <a class="button is-primary" href="{{route('categorie.create')}}">Ajouter</a>


            <table class="table">
                <thead>
                <tr>
                    <th>
                        Titre
                    </th>
                    <th>
                        Auteur
                    </th>
                    <th>
                        Date de publication
                    </th>
                    <th>
                        Date de modification
                    </th>
                </tr>
                </thead>
                <tbody>

                @forelse($page as $p)
                    <tr>

                        <th>
                            <a href="{{ route('categorie.edit', $p->id) }}">
                                {{ $p->name }}
                            </a>
                        </th>
                        <th>
                            <a href="{{ route('categorie.show', $p->id) }}">
                                Voir
                            </a>
                        </th>
                    </tr>
                @empty
                    <p>Il n'y a pas encore de catégories de page !</p>

            @endforelse
                </tbody>
            </table>

        </div>

    </section>

@stop

resources/views/admin/categorie/show.blade.php
@extends('layouts.admin.admin')
@section('content')

    <section class="section">

        <div class="container">

            <h1 class="title">{{ $page->name }}</h1>
            <div class='body'>
               <p> {!! $page->description !!}</p>
            </div>
        </div>

    </section>

@stop